/**
  ******************************************************************************
  * Ten Tep		:		  MTP4x4.h
  * Tac Gia		:	  	LE ANH QUANG
  * Cong Ty		:			MinhHaGroup
  *	Website 	:			MinhHaGroup.com
  * Phien Ban	:			V1.0.0
  * Ngay			:    	19-9-2012
  * Tom Tat   :     Khai bao cac ham su dung trong tep MTP4x4.c
  *           
  *
  ******************************************************************************
  * Chu Y		:
  *							 
  ******************************************************************************
  */
	
#ifndef __MTP4x4_H
#define __MTP4x4_H

#include <main.h>

// Ham thuc hien qua trinh quet phim va tra ve phim duoc bam
unsigned char mtp_quetphim();						

#endif
// ------------------END OF FILE--------------------
// -------------------------------------------------