/**
  ******************************************************************************
  * Ten Tep		:		  var.h
  * Tac Gia		:	  	LE ANH QUANG
  * Cong Ty		:			MinhHaGroup
  *	Website 	:			MinhHaGroup.com
  * Phien Ban	:			V1.0.0
  * Ngay			:    	19-10-2012
  * Tom Tat   :     Khai bao cac bien toan cuc
  *           
  *
  ******************************************************************************
  * Chu Y		:
  *							 
  ******************************************************************************
  */
	

#ifndef __VAR_H
#define __VAR_H
#include "main.h"
//unsigned char hour,minute,second;
//float Nhiet_Do;							// DS18b20
//static unsigned char Lcd_Buff[30],str[20];	// LCD1602
//unsigned char KEY,i;				// MA TRAN PHIM 4x4, PHIM BAM

  		// UART
	
#endif
// ------------------END OF FILE--------------------



